FROM php:8.2-fpm

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

# Set working directory
WORKDIR /var/www

# Install dependencies
RUN apt-get update && apt-get install -y
RUN apt-get install -y p7zip-full git lsof procps zlib1g-dev libxml2-dev libzip-dev dnsutils iputils-ping net-tools
RUN apt-get install -y supervisor

# Clear cache
RUN apt clean && rm -rf /var/lib/apt/lists/*

# Install extensions
RUN install-php-extensions gd intl mysqli pdo pdo_mysql zip exif pcntl redis swoole bcmath
#RUN docker-php-ext-install intl mysqli pdo pdo_mysql 
#RUN docker-php-ext-install zip exif pcntl

# Install redis
#RUN pecl install redis && docker-php-ext-enable redis

# Install swoole
#RUN pecl install swoole && docker-php-ext-enable swoole

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy supervisor workers for laravel
ADD ./laravel-workers.conf /etc/supervisor/conf.d/

# Start server
CMD ["sh", "/var/www/start-server.sh"]
